BEGIN;

CREATE TABLE IF NOT EXISTS public.user_blacklist (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  student_number text,
  university_email text,
  reason text NOT NULL,
  active boolean NOT NULL DEFAULT true,
  expires_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  created_by uuid,
  updated_at timestamptz NOT NULL DEFAULT now(),
  removed_at timestamptz,
  removed_by uuid,
  CONSTRAINT user_blacklist_identifier_required
    CHECK (student_number IS NOT NULL OR university_email IS NOT NULL)
);

CREATE UNIQUE INDEX IF NOT EXISTS user_blacklist_active_student_number_uidx
  ON public.user_blacklist(student_number)
  WHERE active AND student_number IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS user_blacklist_active_email_uidx
  ON public.user_blacklist(university_email)
  WHERE active AND university_email IS NOT NULL;

ALTER TABLE public.user_blacklist ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS user_blacklist_admin_select ON public.user_blacklist;
CREATE POLICY user_blacklist_admin_select
ON public.user_blacklist
FOR SELECT
TO authenticated
USING (EXISTS (
  SELECT 1 FROM public.admin_users au WHERE au.user_id = auth.uid()
));

DROP POLICY IF EXISTS user_blacklist_admin_insert ON public.user_blacklist;
CREATE POLICY user_blacklist_admin_insert
ON public.user_blacklist
FOR INSERT
TO authenticated
WITH CHECK (EXISTS (
  SELECT 1 FROM public.admin_users au WHERE au.user_id = auth.uid()
));

DROP POLICY IF EXISTS user_blacklist_admin_update ON public.user_blacklist;
CREATE POLICY user_blacklist_admin_update
ON public.user_blacklist
FOR UPDATE
TO authenticated
USING (EXISTS (
  SELECT 1 FROM public.admin_users au WHERE au.user_id = auth.uid()
))
WITH CHECK (EXISTS (
  SELECT 1 FROM public.admin_users au WHERE au.user_id = auth.uid()
));

DROP POLICY IF EXISTS user_blacklist_admin_delete ON public.user_blacklist;
CREATE POLICY user_blacklist_admin_delete
ON public.user_blacklist
FOR DELETE
TO authenticated
USING (EXISTS (
  SELECT 1 FROM public.admin_users au WHERE au.user_id = auth.uid()
));

CREATE TABLE IF NOT EXISTS public.admin_action_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  action text NOT NULL,
  target_table text NOT NULL,
  target_id text,
  details jsonb NOT NULL DEFAULT '{}'::jsonb,
  actor_user_id uuid,
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.admin_action_logs ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS admin_action_logs_admin_select ON public.admin_action_logs;
CREATE POLICY admin_action_logs_admin_select
ON public.admin_action_logs
FOR SELECT
TO authenticated
USING (EXISTS (
  SELECT 1 FROM public.admin_users au WHERE au.user_id = auth.uid()
));

CREATE OR REPLACE FUNCTION public.normalize_blacklist_entry()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_student text;
BEGIN
  IF NEW.student_number IS NOT NULL THEN
    v_student := upper(regexp_replace(btrim(NEW.student_number), '\s+', '', 'g'));
    IF v_student LIKE 'S%' THEN
      v_student := substr(v_student, 2);
    END IF;
    NEW.student_number := NULLIF(v_student, '');
  END IF;

  IF NEW.university_email IS NOT NULL THEN
    NEW.university_email := NULLIF(lower(btrim(NEW.university_email)), '');
  END IF;

  NEW.reason := btrim(NEW.reason);
  NEW.updated_at := now();

  IF TG_OP = 'INSERT' THEN
    NEW.created_by := COALESCE(NEW.created_by, auth.uid());
  END IF;

  IF NEW.active IS FALSE THEN
    IF TG_OP = 'INSERT' OR OLD.active IS DISTINCT FROM FALSE THEN
      NEW.removed_at := COALESCE(NEW.removed_at, now());
      NEW.removed_by := COALESCE(NEW.removed_by, auth.uid());
    END IF;
  ELSIF NEW.active IS TRUE THEN
    NEW.removed_at := NULL;
    NEW.removed_by := NULL;
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS user_blacklist_normalize ON public.user_blacklist;
CREATE TRIGGER user_blacklist_normalize
BEFORE INSERT OR UPDATE ON public.user_blacklist
FOR EACH ROW EXECUTE FUNCTION public.normalize_blacklist_entry();

CREATE OR REPLACE FUNCTION public.is_user_blacklisted(
  p_student_number text,
  p_university_email text
)
RETURNS boolean
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_student text;
  v_email text;
BEGIN
  v_student := upper(regexp_replace(btrim(COALESCE(p_student_number, '')), '\s+', '', 'g'));
  IF v_student LIKE 'S%' THEN
    v_student := substr(v_student, 2);
  END IF;
  v_email := lower(btrim(COALESCE(p_university_email, '')));

  RETURN EXISTS (
    SELECT 1
    FROM public.user_blacklist b
    WHERE b.active
      AND (b.expires_at IS NULL OR b.expires_at > now())
      AND (
        (v_student <> '' AND b.student_number = v_student)
        OR (v_email <> '' AND b.university_email = v_email)
      )
  );
END;
$$;

REVOKE ALL ON FUNCTION public.is_user_blacklisted(text, text) FROM PUBLIC;

CREATE OR REPLACE FUNCTION public.enforce_reservation_blacklist()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF public.is_user_blacklisted(NEW.student_number, NEW.university_email) THEN
    RAISE EXCEPTION '現在このサービスを利用できません。';
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS reservations_enforce_blacklist ON public.reservations;
CREATE TRIGGER reservations_enforce_blacklist
BEFORE INSERT ON public.reservations
FOR EACH ROW EXECUTE FUNCTION public.enforce_reservation_blacklist();

CREATE OR REPLACE FUNCTION public.audit_blacklist_change()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_action text;
  v_id uuid;
  v_details jsonb;
BEGIN
  IF TG_OP = 'INSERT' THEN
    v_action := 'blacklist_add';
    v_id := NEW.id;
    v_details := to_jsonb(NEW);
  ELSIF TG_OP = 'UPDATE' THEN
    v_action := CASE
      WHEN OLD.active IS TRUE AND NEW.active IS FALSE THEN 'blacklist_remove'
      WHEN OLD.active IS FALSE AND NEW.active IS TRUE THEN 'blacklist_restore'
      ELSE 'blacklist_update'
    END;
    v_id := NEW.id;
    v_details := jsonb_build_object('before', to_jsonb(OLD), 'after', to_jsonb(NEW));
  ELSE
    v_action := 'blacklist_delete';
    v_id := OLD.id;
    v_details := to_jsonb(OLD);
  END IF;

  INSERT INTO public.admin_action_logs(
    action, target_table, target_id, details, actor_user_id
  ) VALUES (
    v_action, 'user_blacklist', v_id::text, v_details, auth.uid()
  );

  IF TG_OP = 'DELETE' THEN
    RETURN OLD;
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS user_blacklist_audit ON public.user_blacklist;
CREATE TRIGGER user_blacklist_audit
AFTER INSERT OR UPDATE OR DELETE ON public.user_blacklist
FOR EACH ROW EXECUTE FUNCTION public.audit_blacklist_change();

INSERT INTO public.user_blacklist (
  student_number,
  university_email,
  reason,
  active
)
SELECT
  '26P080',
  's26p080@ge.osaka-sandai.ac.jp',
  '2026-07-23の2日目に、発行記録のない状態で1日目の未使用当日券を提示したため。',
  true
WHERE NOT EXISTS (
  SELECT 1
  FROM public.user_blacklist
  WHERE active
    AND (
      student_number = '26P080'
      OR university_email = 's26p080@ge.osaka-sandai.ac.jp'
    )
);

DROP FUNCTION IF EXISTS public.find_ticket(uuid, uuid, text, text, text);
CREATE FUNCTION public.find_ticket(
  p_event_id uuid,
  p_event_slot_id uuid,
  p_student_name text,
  p_student_number text,
  p_university_email text
)
RETURNS text
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_public_token text;
  v_student_number text;
  v_email text;
BEGIN
  v_student_number := upper(regexp_replace(btrim(COALESCE(p_student_number, '')), '\s+', '', 'g'));
  IF v_student_number LIKE 'S%' THEN
    v_student_number := substr(v_student_number, 2);
  END IF;
  v_email := lower(btrim(COALESCE(p_university_email, '')));

  IF public.is_user_blacklisted(v_student_number, v_email) THEN
    RETURN NULL;
  END IF;

  SELECT r.public_token
    INTO v_public_token
  FROM public.reservations r
  JOIN public.events e ON e.id = r.event_id
  LEFT JOIN public.event_slots es ON es.id = r.event_slot_id
  WHERE r.event_id = p_event_id
    AND r.event_slot_id = p_event_slot_id
    AND r.student_name = btrim(p_student_name)
    AND r.student_number = v_student_number
    AND r.university_email = v_email
    AND r.status IN ('reserved', 'used')
    AND (
      CASE
        WHEN r.ticket_type = 'walkin' THEN
          COALESCE(es.walkin_use_ends_at, es.walkin_ends_at, es.ticket_use_ends_at, e.use_ends_at, es.ends_at)
        ELSE
          COALESCE(es.reservation_use_ends_at, es.ticket_use_ends_at, e.use_ends_at, es.ends_at)
      END IS NULL
      OR now() <= CASE
        WHEN r.ticket_type = 'walkin' THEN
          COALESCE(es.walkin_use_ends_at, es.walkin_ends_at, es.ticket_use_ends_at, e.use_ends_at, es.ends_at)
        ELSE
          COALESCE(es.reservation_use_ends_at, es.ticket_use_ends_at, e.use_ends_at, es.ends_at)
      END
    )
  ORDER BY r.created_at DESC
  LIMIT 1;

  RETURN v_public_token;
END;
$$;

REVOKE ALL ON FUNCTION public.find_ticket(uuid, uuid, text, text, text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.find_ticket(uuid, uuid, text, text, text) TO anon, authenticated;

DROP FUNCTION IF EXISTS public.get_ticket(text);
CREATE FUNCTION public.get_ticket(p_public_token text)
RETURNS TABLE(
  reservation_id uuid,
  student_name text,
  student_number text,
  status text,
  ticket_type text,
  ticket_code text,
  public_token text,
  used_at timestamptz,
  cancelled_at timestamptz,
  created_at timestamptz,
  event_id uuid,
  event_title text,
  event_description text,
  event_starts_at timestamptz,
  event_ends_at timestamptz,
  use_starts_at timestamptz,
  use_ends_at timestamptz,
  ticket_enabled boolean,
  use_button_enabled boolean,
  survey_after_reservation_enabled boolean,
  survey_after_reservation_url text,
  survey_after_reservation_message text,
  survey_after_use_enabled boolean,
  survey_after_use_url text,
  survey_after_use_message text,
  post_reservation_notes text,
  is_ticket_use_suspended boolean,
  auto_suspend_at timestamptz,
  slot_id uuid,
  slot_label text,
  slot_starts_at timestamptz,
  slot_ends_at timestamptz,
  slot_reservation_starts_at timestamptz,
  slot_reservation_ends_at timestamptz,
  slot_ticket_use_starts_at timestamptz,
  slot_ticket_use_ends_at timestamptz,
  slot_walkin_starts_at timestamptz,
  slot_walkin_ends_at timestamptz,
  slot_is_reservation_enabled boolean,
  slot_is_ticket_use_enabled boolean,
  slot_is_walkin_enabled boolean,
  slot_reservation_use_starts_at timestamptz,
  slot_reservation_use_ends_at timestamptz,
  slot_walkin_use_starts_at timestamptz,
  slot_walkin_use_ends_at timestamptz
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_event_id uuid;
BEGIN
  SELECT r.event_id
  INTO v_event_id
  FROM public.reservations r
  WHERE r.public_token = p_public_token;

  IF v_event_id IS NOT NULL THEN
    PERFORM public.admin_auto_activate_pre_registrations(v_event_id);
  END IF;

  RETURN QUERY
  SELECT
    r.id,
    r.student_name,
    r.student_number,
    r.status,
    r.ticket_type,
    r.ticket_code,
    r.public_token,
    r.used_at,
    r.cancelled_at,
    r.created_at,
    e.id,
    e.title,
    e.description,
    e.starts_at,
    e.ends_at,
    e.use_starts_at,
    e.use_ends_at,
    e.ticket_enabled,
    e.use_button_enabled,
    e.survey_after_reservation_enabled,
    e.survey_after_reservation_url,
    e.survey_after_reservation_message,
    e.survey_after_use_enabled,
    e.survey_after_use_url,
    e.survey_after_use_message,
    e.post_reservation_notes,
    e.is_ticket_use_suspended,
    e.auto_suspend_at,
    es.id,
    es.label,
    es.starts_at,
    es.ends_at,
    es.reservation_starts_at,
    es.reservation_ends_at,
    es.ticket_use_starts_at,
    es.ticket_use_ends_at,
    es.walkin_starts_at,
    es.walkin_ends_at,
    es.is_reservation_enabled,
    es.is_ticket_use_enabled,
    es.is_walkin_enabled,
    es.reservation_use_starts_at,
    es.reservation_use_ends_at,
    es.walkin_use_starts_at,
    es.walkin_use_ends_at
  FROM public.reservations r
  JOIN public.events e ON e.id = r.event_id
  LEFT JOIN public.event_slots es ON es.id = r.event_slot_id
  WHERE r.public_token = p_public_token
    AND NOT public.is_user_blacklisted(r.student_number, r.university_email)
    AND (
      CASE
        WHEN r.ticket_type = 'walkin' THEN
          COALESCE(es.walkin_use_ends_at, es.walkin_ends_at, es.ticket_use_ends_at, e.use_ends_at, es.ends_at)
        ELSE
          COALESCE(es.reservation_use_ends_at, es.ticket_use_ends_at, e.use_ends_at, es.ends_at)
      END IS NULL
      OR now() <= CASE
        WHEN r.ticket_type = 'walkin' THEN
          COALESCE(es.walkin_use_ends_at, es.walkin_ends_at, es.ticket_use_ends_at, e.use_ends_at, es.ends_at)
        ELSE
          COALESCE(es.reservation_use_ends_at, es.ticket_use_ends_at, e.use_ends_at, es.ends_at)
      END
    );
END;
$$;

GRANT EXECUTE ON FUNCTION public.get_ticket(text) TO anon, authenticated;

CREATE OR REPLACE FUNCTION public.use_ticket(p_public_token text)
RETURNS json
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_reservation public.reservations%ROWTYPE;
  v_event public.events%ROWTYPE;
  v_use_starts_at timestamptz;
  v_use_ends_at timestamptz;
  v_use_enabled boolean;
BEGIN
  SELECT * INTO v_reservation
  FROM public.reservations
  WHERE public_token = p_public_token
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'チケットが見つかりません。';
  END IF;

  IF public.is_user_blacklisted(v_reservation.student_number, v_reservation.university_email) THEN
    RAISE EXCEPTION '現在このサービスを利用できません。';
  END IF;

  IF v_reservation.status = 'cancelled' THEN
    RAISE EXCEPTION 'このチケットはキャンセルされています。';
  END IF;

  IF v_reservation.status = 'used' THEN
    RETURN json_build_object('status', 'used', 'used_at', v_reservation.used_at);
  END IF;

  SELECT * INTO v_event FROM public.events WHERE id = v_reservation.event_id;

  IF v_event.is_ticket_use_suspended
     OR (v_event.auto_suspend_at IS NOT NULL AND now() >= v_event.auto_suspend_at) THEN
    RAISE EXCEPTION '現在、チケットを使用できません。';
  END IF;

  IF v_event.ticket_enabled IS DISTINCT FROM true
     OR v_event.use_button_enabled IS DISTINCT FROM true THEN
    RAISE EXCEPTION 'このイベントではチケットの使用ボタンが有効化されていません。';
  END IF;

  SELECT
    CASE WHEN v_reservation.ticket_type = 'walkin'
      THEN COALESCE(es.walkin_use_starts_at, es.walkin_starts_at, es.ticket_use_starts_at, es.starts_at)
      ELSE COALESCE(es.reservation_use_starts_at, es.ticket_use_starts_at, es.starts_at)
    END,
    CASE WHEN v_reservation.ticket_type = 'walkin'
      THEN COALESCE(es.walkin_use_ends_at, es.walkin_ends_at, es.ticket_use_ends_at, es.ends_at)
      ELSE COALESCE(es.reservation_use_ends_at, es.ticket_use_ends_at, es.ends_at)
    END,
    es.is_ticket_use_enabled
  INTO v_use_starts_at, v_use_ends_at, v_use_enabled
  FROM public.event_slots es
  WHERE es.id = v_reservation.event_slot_id;

  IF v_use_enabled IS DISTINCT FROM true THEN
    RAISE EXCEPTION 'このチケットは使用不可に設定されています。';
  END IF;

  IF v_use_starts_at IS NOT NULL AND now() < v_use_starts_at THEN
    RAISE EXCEPTION 'このチケットはまだ使用できません。';
  END IF;

  IF v_use_ends_at IS NOT NULL AND now() > v_use_ends_at THEN
    RAISE EXCEPTION 'このチケットの使用可能時間は終了しました。';
  END IF;

  UPDATE public.reservations
  SET status = 'used', used_at = now()
  WHERE id = v_reservation.id AND status = 'reserved'
  RETURNING * INTO v_reservation;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'チケットはすでに使用されています。';
  END IF;

  RETURN json_build_object('status', v_reservation.status, 'used_at', v_reservation.used_at);
END;
$$;

GRANT EXECUTE ON FUNCTION public.use_ticket(text) TO anon, authenticated;

NOTIFY pgrst, 'reload schema';
COMMIT;
